### ISSUE TITLE
Server Modes + Realtime + Mediaserver Deployment Configuration

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#136]
We want our monolithic server architecture to be something that can serve all of our backend purposes. In this way, we have server "modes" -- each mode determines, through hooks, which routes are available. The "server mode" will be queryable based on an environment variable depending on how the server is deployed.

We have three main modes:
API Server: Default, current config
Media Server: Only handles heavy media processing and threading tasks (thumbnail crops, videos, resize, etc)
Realtime Gameserver: Handles all realtime world update information for user, part of a gameserver fleet using Agones to do fleet management on Kubernetes

**Comment by barankyle** [comment]
I know we discussed this last week, but just to be clear (and in case there was any change of mind in the interim): should all services be allowed by default unless specifically disallowed? For example, video conversion will be specifically disallowed if the server mode isn't 'media'? Do we want to set out the blacklist for every service, or just the ones that could be problematic, e.g. media services?

**Comment by shawticus** [comment]
@barankyle Just the problematic ones, we'll need to do some auth testing and refactoring at some point anyways.
