### ISSUE TITLE
Handle account merging, account deletion by account provider removal

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#143]
If a user connects an account to their profile that is already connected to another profile, we should warn them and prevent the action.

If a user removes all account providers from their account, their user account (and user settings) will be destroyed as well. This should come with a warning in the add/remove connected accounts module.

**Comment by green9016** [comment]
Hello @shawticus 
When remove a user account, following relations are all destroyed as well.
Please confirm it is correct or wrong.

Destroyed relations( onDelete => CASCADE )
user_settings
collection
entity
user_relationship
group_user
static_resource
asset
owned_file

Restricted Relations ( onDelete => RESTRICT )
identity_provider
