### ISSUE TITLE
Move video rendering to a separate service, possibly do them sequentially

### ISSUE THREAD

**Issue by barankyle** [xrchat/xrchat-server#42]
Rendering just 10 videos at once concurrently on the server is taking a very long time, on the order of an hour. It would likely be better to do this outside of the API server so as not to max it out and cause rendering drops if the API is being redeployed.

Not sure if a standalone server/K8s pod, Lambda, or something else would be the best platform.

Also not sure if doing one at a time from a queue is better than multiple ones at once.

One thing we've considered is giving our server a "mode" type -- so that it can run as a media server and only expose those endpoints, or as an API or realtime gamserver, for example.

**Comment by shawticus** [comment]
Closing this issue because microservice arch should solve this out of the box
