### ISSUE TITLE
Refactor public-video model, merge it into resources model.

### ISSUE THREAD

**Issue by dmitrizagidulin** [xrchat/xrchat-server#52]
Our `public-video`s Model (and database table) currently looks like:

```
    {
   	 "original_title": "My Video",
   	 "title": "The Video Title to be Displayed",
   	 "link": "https://www.youtube.com/watch?v=abc123",
   	 "description": "Some description",
	“thumbnail_url”: “ “something.jpg”,
        "production_credit": "...",
        "rating": "",
        "categories": "...",
        "runtime": "..."
        "tags": "..."

    }
```
This needs to be moved into the Objects model, since that's exactly what Objects were intended for - external assets with a title, link, description, thumbnail.

(This will be a stepping stone to also storing Scene thumbnails in objects, so we can re-use the video grid component for them.)

(Also, drop the `original_title` field - we don't need it.)

**Comment by dmitrizagidulin** [comment]
(@shawticus to tackle this!)

**Comment by shawticus** [comment]
@dmitrizagidulin closing this because we are keeping this endpoint and Kyle has already set up to work with our low level APIs.
