### ISSUE TITLE
Change email subject line to come from config

### ISSUE THREAD

**Issue by thatpassesfor** [xrchat/xrchat-server#53]
(This applies to any auto-generated email, but specifically to the Email Login Link emails.)

Email subject line reads "Magic Link to sign in", 

Expected:  language to mirror the log-in screen and identify the community from which the email is being sent  ex: "Login to KaiXR.com"

Right now the email subject line is hard coded, let's instead draw from config.

**Comment by dmitrizagidulin** [comment]
Implemented in https://github.com/xrchat/xrchat-server/pull/71. Assigning to @thatpassesfor for QA.

**Comment by dmitrizagidulin** [comment]
Working locally, will test on Dev once deploys.

**Comment by shawticus** [comment]
@dmitrizagidulin can we close?

**Comment by dmitrizagidulin** [comment]
Implemented, tested, closing!
