### ISSUE TITLE
Add models

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#6]
Users
Has a Contacts list (their friends)
Has many Avatars
Belongs to many Groups (those are ephemeral though)
Contacts
user_id
contact type (friend, blocked, muted etc)
Groups
group_id (string)
user_id (string)
User_role
current_location
XRAvatar
A 3D Model / skeleton, blob. Multiple standard models/formats. There’ll be a list of public templates, but users can have their own / custom ones.
format_type (VRM model, whatever)
Created_by_attribution
owner
name
thumbnail
XRLocationInstance
A particular location has many Instances, for load balancing users. Users can only talk to other people in the same instance. Instances are dynamically allocated; when you join a location, you’re assigned (round robin at first) to a particular instance. (Think “instance dungeon” in an MMO.)
belongsTo Location
belongsTo Scene (references a scene)
location_id - foreign key
XRLocation (XRSpace from the WebXR spec?)
These are the “rooms” that get listed on the front page (or are unlisted, which you can only access via direct link). UI-wise, users “join” a location, but they’re actually assigned to one of the many instances for that location.
Example: VR Event.
is owned by its creator - a User or a Group. (Unless it’s given to somebody else)
hasMany Instances
name (string, unique) - passphrase-style, like Mozilla Hubs
maxUsersPerInstance (number)
access (string) - public/private access etc
XRObject (Not needed right now)
Is an asset file / image / model.
belongsTo User / Group
many-to-many rel’ with Scene (objects are referenced by many Scenes)
object type (static, to start with - “you put it in the room, it stays there.”)
file format
created by
XRScene
“A user made a thing”. A grouping of objects. A scene is assigned to a Location.
Many-to-many rel’ with Locations.
List of objects (with location, position, location. Object id + transform)
(Ideally conforms with Mozilla Spoke)
ScheduledXRLocation
DateTimeRange (turned on / turned off)
Group
Name
XRScene
Payments
Time
User
Type

**Comment by dmitrizagidulin** [comment]
Models added (aside from ScheduledXRLocation and Payments - will add those separately).
