### ISSUE TITLE
Refactor User data to be stored in IdentityProvider and relational table

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-server#62]
Currently, users carry around a long list of connected identities Since users will need to be referenced fairly often, and account connections are going to end up with a ton of blank tables for most users, we need to refactor to have an "identity_provider" table which stores oauth, sms and e-mail.

Identity provider hasOne account type, belongsTo user.

**Comment by dmitrizagidulin** [comment]
(Assigned to @green9016, in progress.)

**Comment by dmitrizagidulin** [comment]
Implemented in PR #88, tested locally. Closing.
